services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  backend: 
    build: ./backend
    ports:
      # - "3000:3000"
      - "0.0.0.0:3000:3000" #allow access from outside container
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  frontend:
    build:
      context: . # Root directory
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis
      - backend
  
  
  # app:
  #   image: your-image-name
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./app:/app
  #   environment:
  #     - ENV_VAR_NAME=value
  #   networks:
  #     - app-network
